name: flutternew
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages (all used)
  firebase_messaging: ^15.0.3
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  cloud_functions: ^5.6.1
  firebase_analytics: ^11.5.2

  # Core utilities (all used)
  intl: ^0.20.2
  shared_preferences: ^2.4.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.2
  image_cropper: ^9.0.0
  get: ^4.6.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  lottie: ^2.3.2
  font_awesome_flutter: ^10.8.0
  flutter_riverpod: ^2.6.1
  animate_do: ^4.2.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.1.0
  animations: ^2.0.7
  flutter_launcher_icons: ^0.14.3
  mobile_scanner: ^5.1.1
  flutter_map: ^8.2.1
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  http: ^1.3.0
  razorpay_flutter: ^1.4.0
  webview_flutter: ^4.7.0
  vector_math: ^2.1.0
  awesome_notifications: ^0.10.1
  qr_flutter: ^4.1.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  flutter_screenutil: ^5.9.3
  video_player: ^2.10.0
  uuid: ^4.3.3
  youtube_player_flutter: ^9.1.1
  flutter_rating_bar: ^4.0.1
  google_generative_ai: ^0.2.0
  
  # Additional packages that are actually used
  timeline_tile: ^2.0.0
  open_file: ^3.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "icon/img.png"

flutter:
  uses-material-design: true
  assets:
    - icon/img.png
    - images/map.gif
    - images/recycle.gif
    - images/navigation.gif
    - images/profile.jpg
    - json/product.json
    - json/recycledelectronics.json
    - json/recycledpro.json

dependency_overrides:
  flutter_inappwebview: ^6.0.0
  razorpay_flutter: ^1.4.0
  webview_flutter_android: ^3.15.0
